apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
spec:
    replicas: 3
    selector:
        apps: nginx-app
    template:
        metadata:
            name: nginx-pod
            labels:
                apps: nginx-app
        spec:
            containers:
            - name: nginx-container
              image: nginx
              ports:
              - containerPort: 80
