apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx-rs
spec:
    replicas: 2
    selector: 
        matchExpressions:
            - {key: tier, operator: In, values: [frontend]}
            - {key: app, operator: In, values: [nginx-app]}
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx-app
                tier: frontend
        spec:
            containers:
                - name: nginx-container
                  image: nginx
                  ports:
                    - containerPort: 80