apiVersion: v1
kind: Service
metadata:
    name: nginx-svc-np
    labels:
        app: nginx-svc-np
spec:
    selectors:
        app: nginx-app
    type: NodePort
    ports:
        - nodePort: 3100
          port: 80
          targetPort: 80
